homebrew_packages:
  - wget
  - git
  - nkf
  - lua
  - reattach-to-user-namespace
  - tmux
  - vim
  - neovim
  - fish
  - { name: openssl, state: linked, install_options: force }
  - ag
  - tree
  - jq
  - fzf
  - ctags
  - ghq
  - kube-ps1
  - mise
