- name: Get zsh path
  shell: which zsh
  register: zsh_path
  ignore_errors: True

- name: Check current login shell
  shell: echo $SHELL
  register: current_shell

- name: Check if zsh is registered in /etc/shells
  shell: cat /etc/shells | grep {{ zsh_path.stdout }}
  register: zsh_included
  ignore_errors: True

- name: Add zsh path in /etc/shells if it's not included yet
  become: yes
  shell: echo {{ zsh_path.stdout }} >> /etc/shells
  when: zsh_included.rc != 0

- name: Change default shell to zsh
  shell: chsh -s {{ zsh_path.stdout }}
  when: current_shell.stdout != zsh_path.stdout
  register: result
  until: result.rc == 0
  retries: 3

