- name: Install pyenv by Homebrew
  homebrew: name=pyenv-virtualenv

- name: Python2 is installed?
  shell: pyenv versions | grep 2.7.15
  ignore_errors: True
  register: python2_exist

- name: Install Python2
  shell: pyenv install 2.7.15
  when: python2_exist is failed

- name: Python3 is installed?
  shell: pyenv versions 3.10.1
  ignore_errors: True
  register: python3_exist

- name: Install Python3
  shell: pyenv install 3.10.1
  when: python3_exist is failed

- name: Set global Python
  shell: pyenv global 3.10.1

- name: Install pyenvim
  shell: python3 -m pip install pynvim
