- name: Get zsh path
  shell: which zsh
  register: which_zsh
  ignore_errors: True

- name: Check current login shell
  shell: echo $SHELL
  register: current_shell

- name: Check /etc/shells
  shell: cat /etc/shells | grep {{ current_shell.stdout }}
  register: etc_shells

- name: Add zsh pass in /etc/shells
  become: yes
  shell: echo {{ which_zsh.stdout }} >> /etc/shells
  when: etc_shells.stdout != which_zsh.stdout

- name: Change default shell to zsh
  shell: chsh -s {{ which_zsh.stdout }}
  when: current_shell.stdout != which_zsh.stdout
  register: result
  until: result.rc == 0
  retries: 3

