- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew packages
  homebrew:
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{ item.install_options | default() }}
  with_items:
    - "{{ homebrew_packages }}"

