- name: Get fish path
  shell: which fish
  register: fish_path
  ignore_errors: True

- name: Check current login shell
  shell: echo $SHELL
  register: current_shell

- name: Check if fish is registered in /etc/shells
  shell: cat /etc/shells | grep "{{ fish_path.stdout }}"
  register: fish_included
  ignore_errors: True

- name: Add fish path in /etc/shells if it's not included yet
  become: yes
  shell: echo "{{ fish_path.stdout }}" >> /etc/shells
  when: fish_included.rc != 0

- name: Change default shell to fish
  become: yes
  shell: chsh -s "{{ fish_path.stdout }}" "{{ lookup('env', 'USER') }}"
  when: current_shell.stdout != fish_path.stdout
  register: result
  until: result.rc == 0
  retries: 3
