- name: Install pyenv with Homebrew
  homebrew: name=pyenv

- name: Python2.7.12 check
  shell: pyenv versions | grep 2.7.12
  changed_when: False
  failed_when: False
  register: python2_exist

- name: Install Python2.7.12
  shell: pyenv install 2.7.12
  when: python2_exist | failed

- name: Get latest Python
  shell: pyenv install -l | grep -v - | tail -1
  register: latest_python

- name: Check installed Python
  shell: pyenv versions | grep {{ latest_python.stdout }}
  changed_when: False
  failed_when: False
  register: latest_exist

- name: Install Python
  shell: pyenv install {{ latest_python.stdout }}
  when: latest_exist | failed

- name: Set Global Version to {{ latest_python.stdout }}
  shell: pyenv global {{ latest_python.stdout }}

