- name: Install pyenv with Homebrew
  homebrew: name=pyenv-virtualenv

- name: Python2.7.12 check
  shell: pyenv versions | grep 2.7.12
  changed_when: False
  failed_when: False
  register: python2_exist

- name: Install Python2.7.12
  shell: pyenv install 2.7.12
  when: python2_exist is failed

- name: Get latest Python
  shell: pyenv install -l | grep -v - | tail -1
  register: latest_python

- name: Check installed Python
  shell: pyenv versions | grep {{ latest_python.stdout }}
  changed_when: False
  failed_when: False
  register: latest_exist

- name: Install Python
  shell: pyenv install {{ latest_python.stdout }}
  when: latest_exist is failed

- name: Get the latest anaconda
  shell: pyenv install --list | grep anaconda3 | tail -1
  register: latest_anaconda

- name: Check installed anaconda
  shell: pyenv versions | grep {{ latest_anaconda.stdout }}
  changed_when: False
  failed_when: False
  register: latest_anaconda_exist

- name: Install anaconda
  shell: pyenv install {{ latest_anaconda.stdout }}
  when: latest_anaconda_exist is failed

- name: Set Global
  shell: pyenv global {{ latest_anaconda.stdout }}

