- name: Install Python2.7.12
  shell: pyenv install 2.7.12

- name: Get latest Python
  shell: pyenv install -l | grep -v - | tail -1
  register: latest_python

- name: Check installed Python
  shell: pyenv versions | grep {{ latest_python.stdout }}
  changed_when: False
  failed_when: False
  register: result

- name: Install Python
  shell: pyenv install {{ latest_python.stdout }}
  when: result | failed

- name: Set Global Version to {{ latest_python.stdout }}
  shell: pyenv global {{ latest_python }}

