- name: Get latest Ruby
  shell: rbenv install -l | grep -v - | tail -1
  register: latest_ruby

- name: Check Installed Ruby
  shell: rbenv versions | grep {{ latest_ruby.stdout }}
  changed_when: False
  failed_when: False
  register: result

- name: Install Ruby
  shell: rbenv install {{ latest_ruby.stdout }}
  when: result | failed

- name: Set Global Version to {{ latest_ruby.stdout }}
  shell: rbenv global {{ latest_ruby.stdout }}

