- name: Get latest Ruby
  shell: rbenv install -l | grep -v - | tail -1
  register: latest_version

- name: Check installed ruby
  shell: rbenv versions | grep {{ latest_version.stdout }}
  changed_when: False
  failed_when: False
  register: result

- name: Install Ruby
  shell: rbenv install {{ latest_version.stdout }}
  when: result | failed

- name: Set global version to {{ latest_version.stdout }}
  shell: rbenv global {{ latest_version.stdout }}

