- name: The latest Ruby version
  shell: rbenv install -l | grep -v - | tail -1
  register: latest_ruby

- name: The latest Ruby is installed?
  shell: rbenv versions | grep {{ latest_ruby.stdout }}
  ignore_errors: True
  register: result

- name: Install the latest Ruby
  shell: rbenv install {{ latest_ruby.stdout }}
  when: result is failed

- name: Set global Ruby version to {{ latest_ruby.stdout }}
  shell: rbenv global {{ latest_ruby.stdout }}
